import React from 'react';
import { Link } from 'react-router-dom';
import Navbar from '../../components/Navbar';
import Footer from '../../components/Footer';
import ResearchRequestForm from '../../components/ResearchRequestForm';

const intelligenceServices = [
  { icon: 'fa-file-lines', title: 'Custom Research', price: 'Starting at $800', text: 'A decision-ready written brief for one focused question about a Chinese company, technology route, supplier category, product claim, or competitive move.', bullets: ['Typically 5–7 pages with 10–15 relevant Chinese-language sources', 'Evidence table with source links and clear uncertainty notes', 'Delivered in writing within 5–7 business days'], ctaLabel: 'Submit a Research Question', to: '/intelligence#research-request' },
  { icon: 'fa-network-wired', title: 'Supplier & Competitor Mapping', price: 'Scoped to category', text: 'A source-backed first-pass map of the companies, roles, public signals, and open questions in a defined Chinese EV, battery, robotics, or component category.', bullets: ['Supplier, competitor, and category role mapping', 'Public filings, product pages, and Chinese-source trails', 'Designed for pre-diligence — not procurement execution'], ctaLabel: 'Qualify a Map Need', href: '#supplier-map-beta' },
  { icon: 'fa-microscope', title: 'Technology Verification', price: 'Focused scope', text: 'Test whether a headline, launch claim, technical milestone, or manufacturing assertion is supported by what Chinese-language sources actually show.', bullets: ['Claim, mechanism, and evidence separated clearly', 'Primary and public-source verification trail', 'Useful before deeper technical or commercial diligence'], ctaLabel: 'Submit a Research Question', to: '/intelligence#research-request' },
  { icon: 'fa-tower-broadcast', title: 'China Monitoring', price: 'Ongoing', text: 'A lightweight, recurring watch on a defined company set, technology theme, supplier category, or competitive question.', bullets: ['English updates from relevant Chinese-source developments', 'Signals prioritized for a stated decision context', 'Cadence and scope agreed in writing before work begins'], ctaLabel: 'Ask About Monitoring', href: 'mailto:business@voltchina.net?subject=China%20Monitoring%20Inquiry' },
];

const workflow = [
  ['01', 'Submit One Focused Question', 'Describe the company, technology, supplier category, product claim, or competitive issue you need checked.'],
  ['02', 'Receive a Written Scope', 'VoltChina confirms whether the project is suitable and sends the scope, fixed price, exclusions, and delivery date by email.'],
  ['03', 'Approve and Pay', 'Research begins after written approval and payment.'],
  ['04', 'Receive the Brief', 'The completed brief is delivered by email or shared document, followed by one written clarification round.'],
];

const Business: React.FC = () => <div className="min-h-screen bg-slate-950 font-sans">
  <Navbar forceDark />
  <main>
    <section className="relative overflow-hidden pb-20 pt-32 lg:pb-28 lg:pt-44">
      <div className="pointer-events-none absolute left-1/2 top-0 h-full w-full max-w-7xl -translate-x-1/2"><div className="absolute left-10 top-24 hidden h-80 w-80 rounded-full bg-volt/10 blur-[120px] md:block" /><div className="absolute bottom-10 right-10 hidden h-96 w-96 rounded-full bg-blue-900/10 blur-[120px] md:block" /></div>
      <div className="relative z-10 mx-auto max-w-6xl px-4 sm:px-6 lg:px-8"><div className="max-w-4xl">
        <div className="mb-8 inline-flex items-center gap-2 rounded-full border border-slate-800 bg-slate-900 px-3 py-1 text-xs font-semibold text-volt"><i className="fa-solid fa-language" /> China-Source Intelligence</div>
        <h1 className="mb-6 text-4xl font-bold leading-tight tracking-tight text-white md:text-6xl">Source-verified China intelligence for pre-diligence and strategy.</h1>
        <p className="mb-10 max-w-3xl text-lg leading-relaxed text-slate-400 md:text-xl">VoltChina helps small investment firms, independent researchers, boutique consultancies, and corporate strategy teams turn Chinese-language public sources into clear English answers — screened, verified, translated, and explained for a specific business question.</p>
        <div className="flex flex-col gap-3 sm:flex-row"><a href="#research-request" className="rounded-lg bg-volt px-6 py-3 text-center font-bold text-white shadow-lg shadow-volt/20 transition-all hover:bg-volt-hover hover:shadow-volt/40">Submit a Research Question</a><a href="#supplier-map-beta" className="rounded-lg border border-volt/40 bg-slate-950/80 px-6 py-3 text-center font-bold text-white transition-all hover:border-volt hover:bg-slate-900">Qualify a Supplier Map Need</a></div>
      </div></div>
    </section>

    <section className="border-y border-slate-800 bg-slate-900 py-20"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
      <div className="mb-14 max-w-3xl"><p className="mb-4 text-sm font-semibold uppercase tracking-[0.2em] text-volt">VoltChina Intelligence</p><h2 className="mb-4 text-3xl font-bold text-white md:text-4xl">Research built around the decision before you.</h2><p className="text-slate-400">The work starts with a defined question and a public Chinese-source trail — not access claims, introductions, or procurement promises. Choose the narrowest service that will help you decide whether deeper diligence is warranted.</p></div>
      <div className="grid grid-cols-1 gap-6 md:grid-cols-2">{intelligenceServices.map((service) => <ServiceCard key={service.title} {...service} />)}</div>
    </div></section>

    <section className="bg-slate-950 py-20"><div className="mx-auto max-w-6xl px-4 sm:px-6 lg:px-8">
      <div className="mb-8 max-w-3xl"><p className="mb-4 text-sm font-semibold uppercase tracking-[0.2em] text-volt">Custom Research</p><h2 className="mb-4 text-3xl font-bold text-white md:text-4xl">A defined written brief, not an open-ended engagement.</h2><p className="text-slate-400">Final scope, fixed price, and delivery date are confirmed in writing before payment.</p></div>
      <div className="rounded-2xl border border-volt/25 bg-gradient-to-br from-slate-900 via-slate-950 to-slate-900 p-7 md:p-9"><div className="mb-6 flex flex-col gap-3 border-b border-slate-800 pb-6 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-semibold uppercase tracking-[0.18em] text-volt">Starting at $800</p><h3 className="mt-2 text-2xl font-bold text-white">Custom Research Delivery</h3></div><a href="#research-request" className="font-semibold text-volt hover:text-orange-300">Submit a question <i className="fa-solid fa-arrow-right ml-1 text-xs" /></a></div><ul className="grid gap-4 sm:grid-cols-2">{['One clearly defined research question', 'Typically 5–7 pages', 'Approximately 10–15 relevant Chinese-language sources', 'Evidence table with source links', 'Confirmed facts, company claims, inference, and verification gaps separated clearly', 'Clear conclusion and uncertainty notes', 'One written clarification round after delivery', 'Delivered within 5–7 business days', 'Final scope, fixed price, and delivery date confirmed before payment'].map((item) => <li key={item} className="flex gap-3 text-sm leading-relaxed text-slate-300"><i className="fa-solid fa-check mt-1 text-volt" /><span>{item}</span></li>)}</ul></div>
    </div></section>

    <section className="border-y border-slate-800 bg-slate-900 py-20"><div className="mx-auto max-w-6xl px-4 sm:px-6 lg:px-8"><div className="mb-12 max-w-3xl"><p className="mb-4 text-sm font-semibold uppercase tracking-[0.2em] text-volt">How It Works</p><h2 className="mb-4 text-3xl font-bold text-white md:text-4xl">Research Without Meetings.</h2><p className="text-slate-400">A focused written workflow keeps the decision, scope, and evidence trail clear from the start.</p></div><div className="grid gap-5 md:grid-cols-2">{workflow.map(([number, title, text]) => <div key={number} className="rounded-2xl border border-slate-800 bg-slate-950 p-6"><span className="text-sm font-bold tracking-[0.18em] text-volt">{number}</span><h3 className="mb-3 mt-3 text-xl font-bold text-white">{title}</h3><p className="leading-relaxed text-slate-400">{text}</p></div>)}</div><p className="mt-8 text-center text-sm font-medium text-slate-300">The entire workflow is async. No telephone or video meeting is required.</p></div></section>

    <section id="research-request" className="scroll-mt-24 bg-slate-950 py-20 md:scroll-mt-28"><div className="mx-auto grid max-w-6xl gap-10 px-4 sm:px-6 lg:grid-cols-[0.8fr_1.2fr] lg:px-8"><div><p className="mb-4 text-sm font-semibold uppercase tracking-[0.2em] text-volt">Written research request</p><h2 className="mb-5 text-3xl font-bold text-white md:text-4xl">Submit a Research Question</h2><p className="max-w-xl text-lg leading-relaxed text-slate-300">Tell us the exact question you need checked from Chinese-language public sources. VoltChina will review the request and reply by email with a written scope, fixed price, and delivery date.</p><div className="mt-8 space-y-4 text-sm text-slate-400"><p className="flex gap-3"><i className="fa-solid fa-file-lines mt-1 text-volt" /><span>One focused question is more useful than a broad topic.</span></p><p className="flex gap-3"><i className="fa-solid fa-language mt-1 text-volt" /><span>Public Chinese-source evidence is screened, translated, and explained in English.</span></p><p className="flex gap-3"><i className="fa-solid fa-envelope mt-1 text-volt" /><span>Scope, price, delivery, and follow-up are handled in writing.</span></p></div></div><ResearchRequestForm /></div></section>

    <section id="supplier-map-beta" className="scroll-mt-24 bg-slate-950 pb-20 md:scroll-mt-28"><div className="mx-auto max-w-6xl px-4 sm:px-6 lg:px-8"><div className="relative overflow-hidden rounded-3xl border border-volt/25 bg-gradient-to-br from-slate-900 via-slate-950 to-slate-900 p-8 shadow-2xl shadow-volt/10 md:p-12"><div className="absolute -right-24 -top-24 h-56 w-56 rounded-full bg-volt/10 blur-3xl" /><div className="relative z-10 grid gap-10 lg:grid-cols-[0.88fr_1.12fr] lg:items-start"><div><div className="mb-5 inline-flex items-center gap-2 rounded-full border border-volt/30 bg-volt/10 px-3 py-1 text-xs font-bold uppercase tracking-[0.18em] text-volt"><i className="fa-solid fa-flask" /> Founding Edition Test</div><h2 className="mb-4 text-3xl font-bold tracking-tight text-white md:text-4xl">Help define one verified supplier map.</h2><p className="max-w-xl text-lg leading-relaxed text-slate-300">This is not a generic waitlist. Tell us the exact Chinese supplier category you need and the decision it would support. We will look for 5–10 comparable paid-use cases before choosing a founding edition.</p><ul className="mt-7 space-y-4 text-sm text-slate-300"><li className="flex gap-3"><i className="fa-solid fa-check mt-1 text-volt" /><span>Specific category, suppliers, and public Chinese-source trail</span></li><li className="flex gap-3"><i className="fa-solid fa-check mt-1 text-volt" /><span>Clear coverage limits, verification gaps, and update date</span></li><li className="flex gap-3"><i className="fa-solid fa-check mt-1 text-volt" /><span>Built around a decision use case — not curiosity alone</span></li></ul></div><SupplierMapForm /></div></div></div></section>

    <section className="border-t border-slate-800 bg-slate-900 py-20"><div className="mx-auto max-w-4xl px-4 text-center sm:px-6 lg:px-8"><h2 className="mb-4 text-3xl font-bold text-white md:text-4xl">Start with one concrete question.</h2><p className="mb-8 text-lg text-slate-400">One company, one technology route, one supplier category, or one claim you need checked from Chinese sources.</p><a href="#research-request" className="inline-flex items-center justify-center gap-2 rounded-lg bg-volt px-7 py-4 font-bold text-white shadow-lg shadow-volt/20 transition-all hover:bg-volt-hover hover:shadow-volt/40"><i className="fa-solid fa-file-lines" /> Submit a Research Question</a><p className="mt-6 text-sm text-slate-500">Looking for sponsorship or a product explainer? Visit <Link to="/media" className="text-slate-300 underline decoration-slate-600 underline-offset-4 hover:text-white">VoltChina Media</Link>.</p></div></section>
  </main>
  <Footer />
</div>;

type ServiceCardProps = { icon: string; title: string; price: string; text: string; bullets: string[]; ctaLabel: string; href?: string; to?: string };
const ServiceCard: React.FC<ServiceCardProps> = ({ icon, title, price, text, bullets, ctaLabel, href, to }) => { const body = <><span>{ctaLabel}</span><i className="fa-solid fa-arrow-right text-xs transition-transform duration-300 group-hover/cta:translate-x-1" /></>; const className = 'group/cta mt-8 inline-flex w-full items-center justify-center gap-2 rounded-lg border border-slate-700 bg-slate-900 px-4 py-3 text-sm font-bold text-white transition-all hover:border-volt/70 hover:bg-slate-800'; return <div className="group relative overflow-hidden rounded-2xl border border-slate-800 bg-slate-950 p-8 transition-all duration-300 hover:-translate-y-1 hover:border-volt/60 hover:shadow-2xl hover:shadow-volt/10"><div className="pointer-events-none absolute -right-20 -top-20 h-40 w-40 rounded-full bg-volt/10 opacity-0 blur-3xl transition-opacity duration-500 group-hover:opacity-100" /><div className="relative z-10 mb-6 flex items-start justify-between gap-4"><div className="flex h-11 w-11 items-center justify-center rounded-full bg-volt/10"><i className={`fa-solid ${icon} text-volt`} /></div><div className="text-right text-lg font-bold text-white">{price}</div></div><h3 className="relative z-10 mb-3 text-xl font-bold text-white">{title}</h3><p className="relative z-10 mb-6 text-sm leading-relaxed text-slate-400">{text}</p><ul className="relative z-10 space-y-3">{bullets.map((item) => <li key={item} className="flex items-start gap-3 text-sm text-slate-300"><i className="fa-solid fa-check mt-1 text-volt" /><span>{item}</span></li>)}</ul>{to ? <Link to={to} className={className}>{body}</Link> : <a href={href} className={className}>{body}</a>}</div>; };

const SupplierMapForm: React.FC = () => <form name="supplier-map-beta" method="POST" action="/supplier-map-beta/thanks" data-netlify="true" data-netlify-honeypot="bot-field" className="rounded-2xl border border-slate-800 bg-slate-950/80 p-6 md:p-7"><input type="hidden" name="form-name" value="supplier-map-beta" /><p className="hidden"><label>Do not fill this out if you are human: <input name="bot-field" /></label></p><div className="grid gap-5 sm:grid-cols-2"><Field label="Your role and company" name="role_company" placeholder="e.g. Principal, Northstar Capital" required /><Field label="Work email" name="work_email" type="email" placeholder="you@company.com" required /><Field label="Supplier category needed" name="supplier_category" placeholder="e.g. China EMB suppliers" required /><SelectField label="How soon do you need it?" name="timeline" required options={['Within 2 weeks', '2–6 weeks', 'This quarter', 'Exploring for later']} /><SelectField label="Preferred format" name="preferred_format" required options={['Verified PDF / map', 'Searchable spreadsheet', 'Short written brief', 'Interactive database']} /><SelectField label="Would you pay for a verified version?" name="paid_interest" required options={['Yes — for the right coverage', 'Maybe — depends on scope', 'No — research only']} /><div className="sm:col-span-2"><SelectField label="Acceptable price range for one verified category" name="budget_range" required options={['Under $250', '$250–500', '$500–1,000', '$1,000+', 'Need to discuss']} /></div><div className="sm:col-span-2"><TextArea label="What decision will this map support?" name="decision" placeholder="e.g. decide whether to begin deeper diligence on China traction suppliers for an investment thesis" required rows={4} /></div></div><button type="submit" className="mt-6 inline-flex w-full items-center justify-center gap-2 rounded-lg bg-volt px-5 py-3 font-bold text-white shadow-lg shadow-volt/20 transition-all hover:bg-volt-hover hover:shadow-volt/40">Share My Map Requirement <i className="fa-solid fa-arrow-right text-xs" /></button><p className="mt-3 text-center text-xs leading-relaxed text-slate-500">Your answers qualify a possible paid founding edition; they do not create a purchase obligation.</p></form>;

const Field: React.FC<{ label: string; name: string; placeholder: string; type?: string; required?: boolean }> = ({ label, name, placeholder, type = 'text', required = false }) => <div><label htmlFor={name} className="mb-2 block text-sm font-medium text-slate-200">{label}</label><input id={name} name={name} type={type} placeholder={placeholder} required={required} className="w-full rounded-lg border border-slate-700 bg-slate-900 px-3 py-3 text-white outline-none transition-colors placeholder:text-slate-500 focus:border-volt focus:ring-1 focus:ring-volt" /></div>;
const TextArea: React.FC<{ label: string; name: string; placeholder: string; required?: boolean; rows: number }> = ({ label, name, placeholder, required = false, rows }) => <div><label htmlFor={name} className="mb-2 block text-sm font-medium text-slate-200">{label}</label><textarea id={name} name={name} required={required} rows={rows} placeholder={placeholder} className="w-full rounded-lg border border-slate-700 bg-slate-900 px-3 py-3 text-white outline-none transition-colors placeholder:text-slate-500 focus:border-volt focus:ring-1 focus:ring-volt" /></div>;
const SelectField: React.FC<{ label: string; name: string; options: string[]; required?: boolean }> = ({ label, name, options, required = false }) => <div><label htmlFor={name} className="mb-2 block text-sm font-medium text-slate-200">{label}</label><select id={name} name={name} required={required} defaultValue="" className="w-full rounded-lg border border-slate-700 bg-slate-900 px-3 py-3 text-white outline-none transition-colors focus:border-volt focus:ring-1 focus:ring-volt"><option value="" disabled>Select one</option>{options.map((option) => <option key={option} value={option}>{option}</option>)}</select></div>;

export default Business;
